name: Docker build and deploy
on:
  push:
    branches: 
     - main
  #pull_request:
    #branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # DockerHub-Benutzername als Secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # DockerHub-Passwort/Token als Secret
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/my-image-name:$(date +%s)
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build package
        run: |
          tar -czf deploy.tar.gz docker-compose.yaml
      - name: Deploy files
        uses: betanzos/scp-upload@v1
        with:
          source: deploy.tar.gz
          host: example.org
          port: 22
          username: hans
          remote_dir: /opt/docker/stage
          recursive: false
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: example.org
          port: 22
          username: hans
          script: |
            tar -xzf deploy.tar.gz
            ls -laFh
          
          

  
